### ISSUE TITLE
Results not shown

### ISSUE THREAD

**Issue by JustdoITcom** [nanmi/YOLOX-deepstream#8]
Thanks for your job

I am currently using xavier nx.
I want to use deepstream there, but the detection result is not displayed.

I got the model_trt.engine pth file using trt.py provided at https://github.com/Megvii-BaseDetection/YOLOX address.

Do I have to get the engine file using the method you mentioned at https://zhuanlan.zhihu.com/p/391693130?

Thank you

**Comment by lantudou** [comment]
Hi, Please refer to this issue 
#5

**Comment by tulbureandreit** [comment]
@JustdoITcom could you offer a bit more detail about your problem?

**Comment by JustdoITcom** [comment]
> @JustdoITcom could you offer a bit more detail about your problem?

I made the engine file properly and turned on deepstream detection, but I didn't get any result box on the screen.

However, thanks to lantudou, I solved it with net-scale-factor=1 instead of net-scale-factor=0.0039215697906911373.

**Comment by tulbureandreit** [comment]
@JustdoITcom thanks. which kind of model did you use?  I struggle using yolox-nano or tiny. Inference won`t run unless I use yolox-s

**Comment by JustdoITcom** [comment]
> @JustdoITcom thanks. which kind of model did you use? I struggle using yolox-nano or tiny. Inference won`t run unless I use yolox-s

I also used yolox-s . I haven't tried tiny and nano.

**Comment by lantudou** [comment]
please check if your model input setting is correct. because the yolox-tiny and nano input size is 416 and 416. not 640*640



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 14, 2022 10:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nanmi/YOLOX-deepstream] Results not shown (#8)




  
@JustdoITcom thanks. which kind of model did you use? I struggle using yolox-nano or tiny. Inference won`t run unless I use yolox-s
  
I also used yolox-s . I haven't tried tiny and nano.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tulbureandreit** [comment]
@lantudou yep. Can jetson xavier support depthwise convolution operations?

**Comment by lantudou** [comment]
you can check the supported operators for your installed tensorrt version. i think the answer is yes



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 14, 2022 20:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nanmi/YOLOX-deepstream] Results not shown (#8)




 
@lantudou yep. Can jetson xavier support depthwise convolution operations?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
